name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: nextjs-build
        path: ./app
	run-id: ${{ github.event.workflow_run.id }}

    - name: Verify files
      run: dir ./app/.next
      shell: pwsh

    - name: Install production dependencies
      run: npm install --production
      working-directory: ./app

    - name: Set environment variables
      run: |
        echo "NODE_ENV=production" >> $env:GITHUB_ENV
        echo "PORT=3000" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Start Next.js app with PM2
      run: |
        npm install -g pm2
        pm2 stop next-app || true
        pm2 start npm --name "next-app" -- start
      working-directory: ./app
      shell: pwsh
