name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Allow PowerShell scripts for this job
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
        shell: pwsh

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: ./app/.next

      - name: Install dependencies
        run: npm install
        shell: pwsh

      - name: Start Next.js app
        run: npm start
        shell: pwsh
