# =======================================
# CI Workflow - Build Next.js
# =======================================
name: CI - Build Next.js

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set PowerShell Execution Policy (process only)
        run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        shell: pwsh

      - name: Install dependencies
        run: npm install
        shell: pwsh

      - name: Build Next.js
        run: npm run build
        shell: pwsh

      - name: Archive build output
        run: Compress-Archive -Path .next -DestinationPath nextjs-build.zip
        shell: pwsh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: nextjs-build.zip

# =======================================
# CD Workflow - Deploy Next.js
# =======================================
name: CD - Deploy Next.js

on:
  workflow_run:
    workflows: ["CI - Build Next.js"]
    types: 
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .

      - name: Extract build artifact
        run: Expand-Archive -Path nextjs-build.zip -DestinationPath .next -Force
        shell: pwsh

      - name: Deploy
        run: |
          echo "Deploying Next.js build..."
          Get-ChildItem -Recurse .next
          # Add your actual deployment commands here
        shell: pwsh
