name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Build Next.js app
      run: npm run build

    - name: Create artifact (zip)
      run: Compress-Archive -Path * -DestinationPath artifact.zip
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: artifact.zip
