name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build Next.js app
        run: npm run build

      - name: Create artifact folder
        run: mkdir ${{ github.workspace }}\artifact

      - name: Create zip artifact
        run: Compress-Archive -Path @(".next","public","package.json","package-lock.json") -DestinationPath ${{ github.workspace }}\artifact\artifact.zip
        shell: powershell

      - name: List artifact contents (debug)
        run: Expand-Archive -Path ${{ github.workspace }}\artifact\artifact.zip -DestinationPath ${{ github.workspace }}\temp -Force; dir ${{ github.workspace }}\temp
        shell: powershell

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: ${{ github.workspace }}\artifact\artifact.zip
